In [2]:
import numpy as np
import time

In [3]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


## 1. Numpy array are faster than list(optimized in C)

In [ ]:
# execution time numpy vs python list
size = 1_000_0000

try:
    #python list
    if size <= 1_000_0000:
        py_list = list(range(size))  
    else:
        print("Too much size!! to handle")
    start_time = time.time()
    sq_list = [x**2 for x in py_list]
    end_time = time.time()
    #np array
    if size <= 1_000_0000:
        np_array = np.array(range(size))  
    else:
        print("Too much size!! to handle")
    start_time2 = time.time()
    # vectorisation
    sq_array = np_array ** 2
    end_time2 = time.time()
    # speed calculate
    np_time = round(end_time2 - start_time2, 4)
    list_time = round(end_time - start_time , 4)
    print(f"Numpy Array time = {np_time} seconds")
    
    print(f"Python List time = {list_time} seconds")
    speed = "Numpy Array is speed" if np_time < list_time else "Python List is speed"
    print(speed)
except TypeError:
    print("Give size range less than 1_00_0000")

Numpy Array time = 0.0549 seconds
Python List time = 2.3123 seconds
Numpy Array is speed


## 2. Numpy stores data in continuous memory blocks.

In [21]:
import sys

#memory
py_list_data = sys.getsizeof(py_list) * len(py_list) # to find size of python list using sys package in bytes
print(f"Python list size = {py_list_data} bytes")

np_data = np_array.nbytes # to find numpy size in bytes
print(f"Numpy array size = {np_data} bytes")

memory = "\nNumpy Array occupy less memory than Py_list " if np_data < py_list_data else "\nPython List occupy less memory"
print(memory)

Python list size = 800000560000000 bytes
Numpy array size = 80000000 bytes

Numpy Array occupy less memory than Py_list 


## 3. Numpy Array Creation

In [32]:
# create - from lists
arr1 = np.array([1,2,3,4,5])
print(arr1, type(arr1),"\nData Type:", arr1.dtype, "\nShape (rows,colmn):",arr1.shape)
print("\n")
arr2 = np.array([1,2,3,4,5, "AI/ML"])
print(arr2, type(arr2),"\nData Type:", arr2.dtype,"\nShape (rows,colmn):", arr2.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> 
Data Type: int64 
Shape (rows,colmn): (5,)


['1' '2' '3' '4' '5' 'AI/ML'] <class 'numpy.ndarray'> 
Data Type: <U21 
Shape (rows,colmn): (6,)


In [36]:
# 2d array
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d)
row , col = arr2d.shape
print(f"(Row:{row},Col:{col})") #array dimension (m x n):(row x coloumn)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(Row:3,Col:4)


In [43]:
# create 0's
arr_zero = np.zeros((2,3), dtype="int64") # prefilled
print(arr_zero)
row , col = arr_zero.shape
print(f"(Row:{row},Col:{col})")

[[0 0 0]
 [0 0 0]]
(Row:2,Col:3)


In [49]:
# create 1's
arr_one = np.ones((2,3), dtype="int64") # prefilled
arr_one2 = np.ones((5,))
print(arr_one)
print(arr_one2)
row , col = arr_one.shape
print(f"(Row:{row},Col:{col})")
print(arr_one2, arr_one2.shape)

[[1 1 1]
 [1 1 1]]
[1. 1. 1. 1. 1.]
(Row:2,Col:3)
[1. 1. 1. 1. 1.] (5,)


In [45]:
# create value (ex: 100)
arr_val = np.full((3,4), 100) # prefilled with value
print(arr_val)
row , col = arr_val.shape
print(f"(Row:{row},Col:{col})")

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
(Row:3,Col:4)


In [50]:
# create indentity matrix
arr_val = np.eye(4) # prefilled with value
print(arr_val)
row , col = arr_val.shape
print(f"(Row:{row},Col:{col})")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(Row:4,Col:4)


In [54]:
# create range matrix
arr_val = np.arange(0, 11, 2) # (start=0, end=11, step=2)
print(arr_val)
print(arr_val.shape)

[ 0  2  4  6  8 10]
(6,)


In [60]:
# create evenly spaced array
arr_val = np.linspace(1, 100, 4) 
print(arr_val)
print(arr_val.shape)

arr_val1 = np.linspace(1, 100, 10) 
print(arr_val1)
print(arr_val1.shape)

[  1.  34.  67. 100.]
(4,)
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
(10,)
